### ISSUE TITLE
JS-API Youtube

### ISSUE THREAD

**Issue by SymoxN7** [SymoxN7/movie-base#7]

**Comment by b70b70** [comment]
Embedded youtube video using yotuube's iframe-API:  <script src="https://www.youtube.com/iframe_api"></script>

**Comment by b70b70** [comment]
![Screenshot 2023-09-20 190623](https://github.com/SymoxN7/movie-base/assets/134099889/91a07dd4-16d0-4c62-8e75-bf9e0bad3293)

**Comment by SymoxN7** [comment]
YT and OMDB code merged into the same file. Now working as intended
